TWProject.Web/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TWProject.Attributes;
using TWProject.BusinessLogic.DB;
using TWProject.BusinessLogic.Interfaces;
using TWProject.Domain.Entities.Booking;
using TWProject.Domain.Entities.Car;
using TWProject.Domain.Entities.User;

namespace TWProject.Web.Controllers
{
    [AdminMod]
    public class AdminController : Controller
    {
	    private CarRentalContext db = new CarRentalContext();
       
        public ActionResult Index()
        {
	        return View(db.Cars.ToList());
        }

        public ActionResult UserIndex()
        {
            return View(db.User.ToList());
        }
        public ActionResult BookingsIndex()
        {
            return View(db.Bookings.ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CarDBTable carDBTable = db.Cars.Find(id);
            if (carDBTable == null)
            {
                return HttpNotFound();
            }
            return View(carDBTable);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CarId,Mark,Model,ProductionYear,BodyType,SeatsNum,Color,Odometer,EnginePower,EngineCapacity,PricePerDay,GearboxType,FuelType,ImagePath,IsAvailable")] CarDBTable carDBTable)
        {
            if (ModelState.IsValid)
            {
                db.Cars.Add(carDBTable);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(carDBTable);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CarDBTable carDBTable = db.Cars.Find(id);
            if (carDBTable == null)
            {
                return HttpNotFound();
            }
            return View(carDBTable);
        }

        public ActionResult UserEdit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UDBTable uDBTable = db.User.Find(id);
            if (uDBTable == null)
            {
                return HttpNotFound();
            }
            return View(uDBTable);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CarId,Mark,Model,ProductionYear,BodyType,SeatsNum,Color,Odometer,EnginePower,EngineCapacity,PricePerDay,GearboxType,FuelType,ImagePath,IsAvailable")] CarDBTable carDBTable)
        {
            if (ModelState.IsValid)
            {
                db.Entry(carDBTable).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(carDBTable);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UserEdit([Bind(Include = "UserId,Name,level,Email,RegistrationDate")] UDBTable uDBTable)
        {
            if (ModelState.IsValid)
            {
                db.Entry(uDBTable).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("UserIndex");
            }
            return View(uDBTable);
        }


        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CarDBTable carDBTable = db.Cars.Find(id);
            if (carDBTable == null)
            {
                return HttpNotFound();
            }
            return View(carDBTable);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CarDBTable carDBTable = db.Cars.Find(id);
            db.Cars.Remove(carDBTable);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult UserDelete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UDBTable uDBTable = db.User.Find(id);
            if (uDBTable == null)
            {
                return HttpNotFound();
            }
            return View(uDBTable);
        }

        [HttpPost, ActionName("UserDelete")]
        [ValidateAntiForgeryToken]
        public ActionResult UserDeleteConfirmed(int id)
        {
            UDBTable uDBTable = db.User.Find(id);
            db.User.Remove(uDBTable);
            db.SaveChanges();
            return RedirectToAction("UserIndex");
        }

        public ActionResult BookingsDelete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BookingDBTable bookingDBTable = db.Bookings.Find(id);
            if (bookingDBTable == null)
            {
                return HttpNotFound();
            }
            return View(bookingDBTable);
        }

        [HttpPost, ActionName("BookingsDelete")]
        [ValidateAntiForgeryToken]
        public ActionResult BookingsDeleteConfirmed(int id)
        {
            BookingDBTable bookingDBTable = db.Bookings.Find(id);
            db.Bookings.Remove(bookingDBTable);
            db.SaveChanges();
            return RedirectToAction("BookingsIndex");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TWProject.Web/Controllers/BookingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Caching;
using System.Web.Mvc;
using TWProject.Attributes;
using TWProject.BusinessLogic;
using TWProject.BusinessLogic.DB;
using TWProject.BusinessLogic.Interfaces;
using TWProject.Domain.Entities.Car;
using TWProject.Domain.Entities.User;
using TWProject.Web.Extentions;
using TWProject.Web.Models;

namespace TWProject.Web.Controllers
{
	public class BookingController : Controller
	{
		private readonly ISession _session;

		public BookingController()
		{
			var bl = new BusinessLogic.BusinessLogic();
			_session = bl.GetSessionBL();
		}

		// GET: Booking
		public ActionResult Index()
		{
			if (!IsUserLoggedIn())
			{
				return RedirectToAction("Index", "Login");
			}

			PopulateCarsDropdown();
			return View();
		}

		[HttpPost]
		public async Task<ActionResult> Index(CarBookings booking)
		{
			PopulateCarsDropdown();
			UBookingData data = new UBookingData
			{
				CarId = booking.CarId,
				BookingReturnDate = booking.BookingReturnDate,
				BookingRecievedDate = booking.BookingRecievedDate,
				Email = booking.Email
			};

			var carBooking = await _session.UserBooking(data);

			switch (carBooking.Status)
			{
				case 1:
					ViewBag.ErrorMessage = "Invalid dates";
					break;
				case 2:
					return Redirect(carBooking.SessionUrl);
				case 3:
					ViewBag.ErrorMessage = $"Sorry, car is already booked between {data.BookingRecievedDate} and {data.BookingReturnDate}";
					break;
				
			}
			return View(booking);
		}
		
		private bool IsUserLoggedIn()
		{
			var loginStatus = System.Web.HttpContext.Current.Session["LoginStatus"] as string;
			return loginStatus == "login";
		}
		
		private void PopulateCarsDropdown()
		{
			var cars = _session.GetAllCars(); 
			ViewBag.Cars = new SelectList(cars, "CarId", "Model");
		}

		public ActionResult OrderConfirmation()
		{
			ViewBag.Message = "Your booking has been confirmed!";
			return View();
		}
	}
}

TWProject.Web/Controllers/ListingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TWProject.BusinessLogic.Interfaces;
using TWProject.Web.Models;

namespace TWProject.Web.Controllers
{
    public class ListingController : Controller
    {
        private readonly ISession _session;

        public ListingController()
        {
            var bl = new BusinessLogic.BusinessLogic();
            _session = bl.GetSessionBL();
        }
        // GET: Listing
        public ActionResult Index(IEnumerable<CarListing> cars,IEnumerable<CarBookings> bookings)
        {
            var getCars = _session.GetAllCars();
            var getBookingDates = _session.GetBookingDates();
            cars = getCars.Select(c => new CarListing
            {
                Mark = c.Mark,
                Model = c.Model,
                ProductionYear = c.ProductionYear,
                BodyType = c.BodyType,
                SeatsNum = c.SeatsNum,
                Color = c.Color,
                Odometer = c.Odometer,
                EngineCapacity = c.EngineCapacity,
                EnginePower = c.EnginePower,
                PricePerDay = c.PricePerDay,
                GearboxType = c.GearboxType,
                FuelType = c.FuelType,
                ImagePath = c.ImagePath,
                IsAvailable = c.IsAvailable
            });

            bookings = getBookingDates.Select(b => new CarBookings
            {
                BookingRecievedDate = b.BookingRecievedDate,
                BookingReturnDate = b.BookingReturnDate
            });

            var viewModel = new CarListingViewModel
            {
	            Cars = cars.ToList(),
	            Bookings = bookings.ToList()
            };
			return View(viewModel);
        }

        
    }
}

TWProject.Web/Controllers/UserController.cs
using System;
using System.Web;
using System.Web.Mvc;
using TWProject.BusinessLogic.Interfaces;
using TWProject.Web.Models;
using TWProject.Domain.Entities.User;
using System.Threading.Tasks;
using System.Collections.Generic;
using TWProject.Domain.Entities.Booking;

namespace TWProject.Web.Controllers
{
     public class UserController : Controller
     {
          private readonly ISession _session;

          public UserController()
          {
               var bl = new BusinessLogic.BusinessLogic();
               _session = bl.GetSessionBL();
          }

          public ActionResult Index()
          {
               if (!IsUserLoggedIn())
               {
                    return RedirectToAction("Index", "Login");
               }
               return View();
          }

          public ActionResult ChangePassword()
          {
               return View();
          }

          [HttpPost]
          [ValidateAntiForgeryToken]
          public ActionResult ChangePassword(ChangePasswordModel model)
          {
               if (ModelState.IsValid)
               {
                    var changePasswordData = new UChangePasswordData
                    {
                         Email = model.Email,
                         CurrentPassword = model.CurrentPassword,
                         NewPassword = model.NewPassword,
                         ConfirmPassword = model.ConfirmPassword
                    };

                    var result = _session.ChangePassword(changePasswordData);

                    if (result.Success)
                    {
                         ViewBag.SuccessMessage = "Password changed successfully.";
                         return View();
                    }
                    else
                    {
                         ModelState.AddModelError("", result.ErrorMessage);
                         return View(model);
                    }
               }

               return View(model);
          }

          public ActionResult ChangeEmail()
          {
               return View();
          }

          [HttpPost]
          [ValidateAntiForgeryToken]
          public ActionResult ChangeEmail(ChangeEmailModel model)
          {
               if (ModelState.IsValid)
               {
                    var changeEmailData = new UChangeEmailData
                    {
                         CurrentEmail = model.CurrentEmail,
                         NewEmail = model.NewEmail,
                         Password = model.Password
                    };

                    var result = _session.ChangeEmail(changeEmailData);

                    if (result.Success)
                    {
                         ViewBag.SuccessMessage = "Email changed successfully.";
                         return View();
                    }
                    else
                    {
                         ModelState.AddModelError("", result.ErrorMessage);
                         return View(model);
                    }
               }

               return View(model);
          }
        public ActionResult UserBookings()
        {
            if (!IsUserLoggedIn())
            {
                return RedirectToAction("Index", "Login");
            }

            var user = GetCurrentUser();
            if (user == null)
            {
                return RedirectToAction("Index", "Login");
            }

            var bookings = _session.GetBookingsByUser(user.Id);

            return View(bookings);
        }

        private UserMini GetCurrentUser()
        {
            var cookieValue = HttpContext.Request.Cookies["X-KEY"]?.Value;
            return _session.GetUserByCookie(cookieValue);
        }

        private bool IsUserLoggedIn()
          {
               var loginStatus = System.Web.HttpContext.Current.Session["LoginStatus"] as string;
               return loginStatus == "login";
          }
     }
}

TWProject.Web/Views/Shared/_Footer.cshtml
@{
    ViewBag.Title = "_Footer";
}

<div class="container">
    <div class="row">
        <div class="col-lg-3">
            <h2 class="footer-heading mb-4">About Us</h2>
            <p>CarRental, we're not just in the business of renting cars; we're in the business of creating memories. </p>
            @*<ul class="list-unstyled social">
                <li><a href="#"><span class="icon-facebook"></span></a></li>
                <li><a href="#"><span class="icon-instagram"></span></a></li>
                <li><a href="#"><span class="icon-twitter"></span></a></li>
                <li><a href="#"><span class="icon-linkedin"></span></a></li>
            </ul>*@
        </div>
        <div class="col-lg-8 ml-auto">
            <div class="row">
                <div class="col-lg-3">
                    <h2 class="footer-heading mb-4">Quick Links</h2>
                    <ul class="list-unstyled">
                        <li><a href="@Url.Action("Index","Booking")" class="nav-link">Booking</a></li>
                    </ul>
                   
                </div>
                <div class="col-lg-3">
                    <h2 class="footer-heading mb-4">Resources</h2>
                    <ul class="list-unstyled">
                        <li><a href="@Url.Action("Index","Listing")" class="nav-link">Listing</a></li>
                    </ul>
                </div>
                <div class="col-lg-3">
                    <h2 class="footer-heading mb-4">Support</h2>
                    <ul class="list-unstyled">
                        <li><a href="@Url.Action("About","Home")" class="nav-link">About</a></li>
                    </ul>
                </div>
                <div class="col-lg-3">
                    <h2 class="footer-heading mb-4">Company</h2>
                    <ul class="list-unstyled">
                        <li><a href="@Url.Action("Ab","Home")" class="nav-link">Contact</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
   
</div>

TWProject.Web/Views/Shared/_Header.cshtml
@{
    ViewBag.Title = "_Header";
    var loginStatus = System.Web.HttpContext.Current.Session["LoginStatus"] as string;
}

<div class="container">
    <div class="row align-items-center position-relative">

        <div class="col-3">
            <div class="site-logo">
                <a href="@Url.Action("Index","Home")"><strong>CarRental</strong></a>
            </div>
        </div>

        <div class="col-9  text-right">
            <span class="d-inline-block d-lg-none"><a href="#" class=" site-menu-toggle js-menu-toggle py-5 "><span class="icon-menu h3 text-black"></span></a></span>

            <nav class="site-navigation text-right ml-auto d-none d-lg-block" role="navigation">
                 <ul class="site-menu main-menu js-clone-nav ml-auto ">
                      <li class="active"><a href="@Url.Action("Index","Home")" class="nav-link">Home</a></li>
                      <li><a href="@Url.Action("Index","Listing")" class="nav-link">Listing</a></li>
                      <li><a href="@Url.Action("Index","Booking")" class="nav-link">Booking</a></li>
                      <li><a href="@Url.Action("About","Home")" class="nav-link">About</a></li>
                      <li><a href="@Url.Action("Contact","Home")" class="nav-link">Contact</a></li>
                      @if (loginStatus != "login")
                      {
                           <li><a href="@Url.Action("Index","Login")" class="nav-link">Log in</a></li>
                      }
                      @if (loginStatus == "login")
                      {
                           <li><a href="@Url.Action("Index","User")" class="nav-link">UserPanel</a></li>
                           <li><a href="@Url.Action("Logout","Login")" class="nav-link">Log out</a></li>
                      }
                 </ul>
            </nav>
        </div>
    </div>
</div>

TWProject.Web/Views/Shared/_HeaderAdmin.cshtml
@{
    ViewBag.Title = "_HeaderAdmin";
}

<div class="container">
    <div class="row align-items-center position-relative">

        <div class="col-3">
            <div class="site-logo">
                <a href="@Url.Action("Index","Admin")"><strong>CarRental Admin</strong></a>
            </div>
        </div>

        <div class="col-9  text-right">

            <span class="d-inline-block d-lg-none"><a href="#" class=" site-menu-toggle js-menu-toggle py-5 "><span class="icon-menu h3 text-black"></span></a></span>

            <nav class="site-navigation text-right ml-auto d-none d-lg-block" role="navigation">
                <ul class="site-menu main-menu js-clone-nav ml-auto ">
                    <li><a href="@Url.Action("Index","Admin")" class="nav-link">Cars Section</a></li>
                    <li><a href="@Url.Action("UserIndex","Admin")" class="nav-link">Users Section</a></li>
                    <li><a href="@Url.Action("BookingsIndex","Admin")" class="nav-link">Bookings Section</a></li>
                    <li><a href="@Url.Action("Logout","Login")" class="nav-link">Log out</a></li>
                </ul>
            </nav>
        </div>


    </div>
</div>

TWProject.Web/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!doctype html>
<html lang="en">

<head>
    <title>CarRental</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700;900&display=swap" rel="stylesheet">

    @Styles.Render("~/bundles/icomoon/css")

    @Styles.Render("~/bundles/bootstrap/css")
    @Styles.Render("~/bundles/bootstrap-datepicker/css")
    @Styles.Render("~/bundles/jquery/css")
    @Styles.Render("~/bundles/owl-carousel/css")
    @Styles.Render("~/bundles/owl-default/css")
    @Styles.Render("~/bundles/flaticon/css")
    @Styles.Render("~/bundles/aos/css")

    <!-- MAIN CSS -->
    @Styles.Render("~/bundles/style/css")

</head>

<body>
    <div class="site-wrap" id="home-section">

        <header class="site-navbar site-navbar-target" role="banner">
            @Html.Partial("_Header")
        </header>

        @RenderBody()

        <footer class="site-footer">
            @Html.Partial("_Footer")
        </footer>

    </div>

    @Scripts.Render("~/bundles/jquery/js")
    @Scripts.Render("~/bundles/popper/js")
    @Scripts.Render("~/bundles/bootstrap/js")
    @Scripts.Render("~/bundles/owl-carousel/js")
    @Scripts.Render("~/bundles/jquery-sticky/js")
    @Scripts.Render("~/bundles/jquery-waypoints/js")
    @Scripts.Render("~/bundles/jquery-animate/js")
    @Scripts.Render("~/bundles/jquery-fancybox/js")
    @Scripts.Render("~/bundles/jquery-easing/js")
    @Scripts.Render("~/bundles/bootstrap-datepicker/js")
    @Scripts.Render("~/bundles/aos/js")

    @Scripts.Render("~/bundles/main/js")
    @RenderSection("scripts", required: false)
</body>
</html>

TWProject.Web/Views/Shared/_LayoutAdmin.cshtml
@using System.Web.Optimization
<!doctype html>
<html lang="en">

<head>
    <title>CarRental</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700;900&display=swap" rel="stylesheet">

    @Styles.Render("~/bundles/icomoon/css")

    @Styles.Render("~/bundles/bootstrap/css")
    @Styles.Render("~/bundles/bootstrap-datepicker/css")
    @Styles.Render("~/bundles/jquery/css")
    @Styles.Render("~/bundles/owl-carousel/css")
    @Styles.Render("~/bundles/owl-default/css")
    @Styles.Render("~/bundles/flaticon/css")
    @Styles.Render("~/bundles/aos/css")

    <!-- MAIN CSS -->
    @Styles.Render("~/bundles/style/css")

</head>

<body>
    <div class="site-wrap" id="home-section">

        <header class="site-navbar site-navbar-target" role="banner">
            @Html.Partial("_HeaderAdmin")
        </header>

        @RenderBody()

      

    </div>

    @Scripts.Render("~/bundles/jquery/js")
    @Scripts.Render("~/bundles/popper/js")
    @Scripts.Render("~/bundles/bootstrap/js")
    @Scripts.Render("~/bundles/owl-carousel/js")
    @Scripts.Render("~/bundles/jquery-sticky/js")
    @Scripts.Render("~/bundles/jquery-waypoints/js")
    @Scripts.Render("~/bundles/jquery-animate/js")
    @Scripts.Render("~/bundles/jquery-fancybox/js")
    @Scripts.Render("~/bundles/jquery-easing/js")
    @Scripts.Render("~/bundles/bootstrap-datepicker/js")
    @Scripts.Render("~/bundles/aos/js")

    @Scripts.Render("~/bundles/main/js")
    @RenderSection("scripts", required: false)
</body>
</html>

TWProject.Web/Views/Shared/_LayoutUser.cshtml
@using System.Web.Optimization
<!doctype html>
<html lang="en">

<head>
     <title>CarRental</title>
     <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

     <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700;900&display=swap" rel="stylesheet">

     @Styles.Render("~/bundles/icomoon/css")

     @Styles.Render("~/bundles/bootstrap/css")
     @Styles.Render("~/bundles/bootstrap-datepicker/css")
     @Styles.Render("~/bundles/jquery/css")
     @Styles.Render("~/bundles/owl-carousel/css")
     @Styles.Render("~/bundles/owl-default/css")
     @Styles.Render("~/bundles/flaticon/css")
     @Styles.Render("~/bundles/aos/css")

     <!-- MAIN CSS -->
     @Styles.Render("~/bundles/style/css")

</head>

<body>
     <div class="site-wrap" id="home-section">

          <header class="site-navbar site-navbar-target" role="banner">
               @Html.Partial("_Header")
          </header>

          @RenderBody()

          <footer class="site-footer">
               @Html.Partial("_Footer")
          </footer>

     </div>

     @Scripts.Render("~/bundles/jquery/js")
     @Scripts.Render("~/bundles/popper/js")
     @Scripts.Render("~/bundles/bootstrap/js")
     @Scripts.Render("~/bundles/owl-carousel/js")
     @Scripts.Render("~/bundles/jquery-sticky/js")
     @Scripts.Render("~/bundles/jquery-waypoints/js")
     @Scripts.Render("~/bundles/jquery-animate/js")
     @Scripts.Render("~/bundles/jquery-fancybox/js")
     @Scripts.Render("~/bundles/jquery-easing/js")
     @Scripts.Render("~/bundles/bootstrap-datepicker/js")
     @Scripts.Render("~/bundles/aos/js")

     @Scripts.Render("~/bundles/main/js")
     @RenderSection("scripts", required: false)
</body>
</html>